### ISSUE TITLE
Mib for SK 3311.410-440 not quite correct

### ISSUE THREAD

**Issue by TomW80** [epiecs/carel-pco-mibs#1]
Hello,

First of all thank you for the Mib.
I have tested this with our air conditioner SK 3311.410-440 and found the following:

- The subtree 2606 you mentioned does not exist on my SK 3311.410-440, so I had to remove it to make it work.

![abfrage SK 3311 410-440](https://user-images.githubusercontent.com/54640793/148183728-fcb59224-4e26-49d7-a9c2-214389bc6a11.png)

- The temperature assignment for Server In and Out you have swapped. see picture.

![Fehler-mib](https://user-images.githubusercontent.com/54640793/148183764-83aa6bea-7945-4e05-852e-5382e605936d.PNG)

- at the entry "generalAlarm" there is a different definition, once is ok (0) and once is ok (1). ok must be here always 1.

![generalAlarm](https://user-images.githubusercontent.com/54640793/148183781-47d7f896-2802-465f-98a8-f5a57d0fca54.PNG)

**Comment by epiecs** [comment]
Hi,

The issue with the subtree is correct if you have a normal unconfigured pco card. However the pco card can be used with a lot of chillers, each with a different set of sensors. I documented this behaviour in the readme: https://github.com/epiecs/carel-pco-mibs#configuring-the-pcoweb-card.

The general alarm issue has been fixed, thanks!

Putting the temps like this was a deliberate choice. This is the input of the chiller and the output. Back then I contemplated as well to swap in and out but it seemed to me that this would make it harder to use this mib for monitoring later on.

**Comment by TomW80** [comment]
>  I documented this behaviour in the readme: https://github.com/epiecs/carel-pco-mibs#configuring-the-pcoweb-card.

oh, I had overlooked that.

> Putting the temps like this was a deliberate choice. This is the input of the chiller and the output. Back then I contemplated as well to swap in and out but it seemed to me that this would make it harder to use this mib for monitoring later on.

Ok, but confused when you look at the website, so I changed it.

**Comment by epiecs** [comment]
No problem, changing things to how you like them is what open source is all about :D. I think that this issue can be closed now. Thanks again for the bugreport!
